.Dd May 1, 2019
.Dt APHELIA 1
.Os
.Sh NAME
.Nm aphelia
.Nd the minimalist window manager
.Sh SYNOPSIS
Configuration and manipulation of software functionality should be done through
editing the source code. No configuration files are provided.
.Sh DESCRIPTION
A light-weight, single-file window manager. Produces a small binary with low
resource consumption\&. Useful for focused work and creating a distraction-free
environment.
.Sh KEY-BINDINGS
The default keybindings:
.Bl -tag -width Ds
.It Cm Alt+a
Push window backwords
.It Cm Alt+s
Pull window forward
.It Cm Alt+q
Kill window
.It Cm Alt+Return
Open (Suckless) Simple Terminal (st)
.It Cm Alt+d
Open dmenu
.It Cm Alt+Backspace
Kill window manager
.It Cm Alt+Left Aq Cm click
Move windows
.It Cm Alt+Right Aq Cm click
Resize windows
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr dmenu 1 ,
.Xr st 1
.Sh AUTHORS
Aphelia was written by
.An -nosplit
.An Jarred Vardy Aq Mt jarred.vardy@gmail.com .

This manual page was written by
.An Nuno Teixeira Aq Mt ed.arrakis@gmail.com 
.An and Jarred Vardy Aq Mt jarred.vardy@gmail.com .
